Added missing inputs and outputs for Doxygen
r-abishek/rpp pull request #253
Opened 2024-03-25 09:06 UTC by sampath1117

- Adds input/output pngs for image based augmentations
- Adds gif for voxel based augmentations

2024-03-25 09:07 UTC, sampath1117 commented
@r-abishek 
Please sync your develop branch with latest changes in opensource develop to see the correct file changes

2024-03-25 19:32 UTC, r-abishek requested changes

2024-03-25 19:32 UTC, r-abishek commented on docs/data/doxygenOutputs/geometric_augmentations_resize_crop_mirror_img150x150.png
Please either use a different crop region, or just use the dog/flower image instead here.
Its not possible to figure if its been mirrored or not here.

2024-03-25 19:32 UTC, r-abishek commented on docs/data/doxygenOutputs/geometric_augmentations_resize_mirror_normalize_img150x150.png
Same comment

2024-03-25 19:32 UTC, r-abishek commented on docs/data/doxygenOutputs/effects_augmentations_water_img150x150.png
If there's a way to play with the freq/amp of the wave to show less of the black areas in the 150x150 for the docs, that'll be better.

2024-03-26 12:39 UTC, sampath1117 commented on docs/data/doxygenOutputs/geometric_augmentations_resize_crop_mirror_img150x150.png
Done

2024-03-26 12:39 UTC, sampath1117 commented on docs/data/doxygenOutputs/geometric_augmentations_resize_mirror_normalize_img150x150.png
Done

2024-03-26 12:39 UTC, sampath1117 commented on docs/data/doxygenOutputs/effects_augmentations_water_img150x150.png
Done

2024-03-27 01:00 UTC, r-abishek approved these changes

2024-03-27 01:00 UTC, merged