Resize cubic and lanczos interpolation
r-abishek/rpp pull request #29
Opened 2021-11-03 19:47 UTC by fiona-gladwin

- Add cubic and lanczos interpolation support for both the HOST and HIP backend.
- Add support for F32, F16, U8 and I8 data types of planar and packed versions.
- Modify rpp-unittests and rpp-performancetests accordingly.

2021-11-08 23:05 UTC, r-abishek requested changes
I have similar comments on the GPU side too, but haven't looked in detail. Will take another look after a round of changes.

2021-11-08 23:15 UTC, r-abishek commented on src/include/cpu/rpp_cpu_common.hpp
> +inline void CalculateLanczosCoefficients(float* coeffs, float x, int a)
This one needs to be optimized too. If 'a' is a pre-defined constant as defined in L1137, and you only need [a, 2 * a, 1 / a, a - 1] inside this functionality, please compute them in an array say aParams[4] or lanczosParams[4] and reuse them here. Currently, these 4 constant values are being computed width*height times for every single function call

2021-11-09 10:55 UTC, fiona-gladwin commented on src/include/cpu/rpp_cpu_common.hpp
> +#define RPPPRANGECHECK(value, a, b)     ((value < a) ? a : ((value < b) ? value : b))
Yes erase and water unit tests pass with this mod

2021-11-10 12:59 UTC, fiona-gladwin commented on src/include/cpu/rpp_cpu_common.hpp
> +inline void saturate_pixel(Rpp32f pixel, Rpp8u* dst) {
Done

2021-11-10 13:00 UTC, fiona-gladwin commented on src/include/cpu/rpp_cpu_common.hpp
> +                            for(int k=0; k < kernelSize; k++)
Done

2021-11-10 19:01 UTC, fiona-gladwin commented on src/include/cpu/rpp_cpu_common.hpp
> +            if ((typeid(Rpp16f) == typeid(T)) || (typeid(Rpp16f) == typeid(U)))
Yes, removing the if else condition

2021-11-18 03:45 UTC, r-abishek requested changes

2021-11-18 03:45 UTC, r-abishek commented on src/include/cpu/rpp_cpu_common.hpp
> +    Rpp32f x2 = x * x;
Rpp32f xo2 = 0.5f * x;
    Rpp32f xt3o2 = xo2 * 3.0f;
    Rpp32f xp2 = x * x;
    coeffs[0] = (-xo2 + 1) * xp2 - xo2;
    coeffs[1] = (xt3o2 - 2.5) * xp2 + 1;
    coeffs[2] = -(xt3o2 + 2) * xp2 + xo2;
    coeffs[3] = 1.0f - coeffs[0] - coeffs[1] - coeffs[2];

2021-11-18 03:45 UTC, r-abishek commented on src/include/cpu/rpp_cpu_common.hpp
> +    Rpp32f x2 = x * x;
Please replace with this and check if unit test is passing

2022-03-25 03:04 UTC, closed without merging