RPP Tensor Support - Bitwise NOT on HOST and HIP
r-abishek/rpp pull request #348
Opened 2024-09-30 04:01 UTC by HazarathKumarM

2025-01-29 08:57 UTC, Srihari-mcw commented on include/rppt_tensor_bitwise_operations.h
> + *          srcPtr depth ranges - Rpp8u (0 to 255), Rpp16f (0 to 1), Rpp32f (0 to 1), Rpp8s (-128 to 127).
Change this to only Rpp8u -Similarly for all bitwise ops

2025-01-29 08:58 UTC, Srihari-mcw commented on include/rppt_tensor_bitwise_operations.h
> + * \image html img150x150.png Sample Input1
Sample Input is enough

2025-01-29 08:58 UTC, Srihari-mcw commented on include/rppt_tensor_bitwise_operations.h
> + * \image html img150x150.png Sample Input1
Sample Input is enough

2025-01-29 08:59 UTC, Srihari-mcw commented on include/rppt_tensor_bitwise_operations.h
> + *          srcPtr depth ranges - Rpp8u (0 to 255), Rpp16f (0 to 1), Rpp32f (0 to 1), Rpp8s (-128 to 127).
Change here to Rpp8u -Similar change required in Bitwise AND/OR

2025-01-29 09:04 UTC, Srihari-mcw commented on src/modules/cpu/kernel/bitwise_not.hpp
> +
Add a similar comment
![image](https://github.com/user-attachments/assets/0d186738-10fc-4c25-93e3-9d6de7acda93)

2025-01-29 09:05 UTC, Srihari-mcw commented on src/modules/cpu/kernel/bitwise_not.hpp
> +#include "rpp_cpu_simd.hpp"
Remove rpp_cpu_simd.hpp

2025-01-29 09:05 UTC, Srihari-mcw commented on src/modules/cpu/kernel/bitwise_not.hpp
> +
Remove I8 from that comment also

2025-01-29 09:06 UTC, Srihari-mcw commented on include/rppt_tensor_bitwise_operations.h
> + * \param [in] srcPtr source1 tensor in HIP memory
Just source tensor

2025-01-29 09:07 UTC, Srihari-mcw commented on include/rppt_tensor_bitwise_operations.h
> + * \param [in] srcDescPtr source tensor descriptor (Restrictions - numDims = 4, offsetInBytes >= 0, dataType = U8/F16/F32/I8, layout = NCHW/NHWC, c = 1/3)
Just U8 - All places also pls change

2025-01-29 09:07 UTC, Srihari-mcw commented on include/rppt_tensor_bitwise_operations.h
> + * \param [in] dstDescPtr destination tensor descriptor (Restrictions - numDims = 4, offsetInBytes >= 0, dataType = U8/F16/F32/I8, layout = NCHW/NHWC, c = same as that of srcDescPtr)
Just U8 - All places also pls change

2025-01-29 09:13 UTC, Srihari-mcw commented on src/modules/cpu/kernel/bitwise_not.hpp
> +                    rpp_simd_load(rpp_load96_u8pln3_to_u8pln3, srcPtrTempR, srcPtrTempG, srcPtrTempB, p);    // simd loads
Use rpp_load96_u8_avx instead

2025-01-29 09:14 UTC, Srihari-mcw commented on src/include/cpu/rpp_cpu_simd.hpp
> +inline void rpp_load96_i8pln3_to_u8pln3(Rpp8s *srcPtrR, Rpp8s *srcPtrG, Rpp8s *srcPtrB, __m256i *px)
Remove this function

2025-01-29 09:14 UTC, Srihari-mcw commented on src/include/cpu/rpp_cpu_simd.hpp
> +inline void rpp_store96_u8pln3_to_i8pkd3(Rpp8s *dstPtr, __m256i *px)
Remove this function

2025-01-29 09:14 UTC, Srihari-mcw commented on src/include/cpu/rpp_cpu_simd.hpp
> +inline void rpp_store96_u8pln3_to_i8pln3(Rpp8s *dstPtrR, Rpp8s *dstPtrG, Rpp8s *dstPtrB, __m256i *px)
Remove this function

2025-01-29 09:15 UTC, Srihari-mcw commented on src/modules/cpu/kernel/bitwise_not.hpp
> +                    rpp_simd_load(rpp_load96_u8pln3_to_u8pln3, srcPtrTempR, srcPtrTempG, srcPtrTempB, p);    // simd loads
Use rpp_load96_u8_avx instead

2025-01-29 09:17 UTC, Srihari-mcw commented on src/include/hip/rpp_hip_common.hpp
>  // d_float8 bitwiseAND
d_uchar8*

2025-01-29 09:17 UTC, Srihari-mcw commented on src/include/hip/rpp_hip_common.hpp
>  // d_float8 bitwiseOR
d_uchar8*

2025-01-29 09:17 UTC, Srihari-mcw commented on src/include/hip/rpp_hip_common.hpp
>  __device__ __forceinline__ void rpp_hip_math_bitwiseXor8(d_uchar8 *src1_uc8, d_uchar8 *src2_uc8, d_uchar8 *dst_uc8)
Add a similar comment just before function

2025-01-29 09:19 UTC, Srihari-mcw commented on src/modules/cpu/kernel/bitwise_and.hpp
>  }
Ensure line at end of file

2025-01-29 09:23 UTC, Srihari-mcw commented on src/modules/cpu/kernel/bitwise_not.hpp
> +
Add a similar comment in bitwise and and bitwise or

2025-01-29 09:48 UTC, Srihari-mcw commented on src/modules/hip/kernel/bitwise_and.hpp
> +    rpp_hip_load8_to_uchar8(srcPtr1 + srcIdx, src1Ptr_uc8);
![image](https://github.com/user-attachments/assets/3bad1b8b-0abe-4a93-9ad5-a70263a8d8aa)

U can directly pass the address of instead of src1_uc8 and src2_uc8 instead of having a separate variable. Do change including in XOR and other ops and Run QA once

2025-01-29 09:50 UTC, Srihari-mcw commented on src/modules/hip/kernel/bitwise_and.hpp
> +__device__ void bitwise_and_hip_compute(d_uchar8 *src1_uc8, d_uchar8 *src2_uc8, d_uchar8 *dst_uc8)
![image](https://github.com/user-attachments/assets/9d220125-6838-4132-92fa-d6591acfd68c)
Add a similar comment but only U8 here, change in XOR and other ops also

2025-01-29 09:50 UTC, Srihari-mcw commented on src/modules/hip/kernel/bitwise_not.hpp
> +    uchar* srcPtr_uc8 = (uchar*)&src_uc8;
Similar change

2025-01-29 09:54 UTC, Srihari-mcw commented on src/modules/hip/kernel/bitwise_or.hpp
> +    uchar* src1Ptr_uc8 = (uchar*)&src1_uc8;
Same comment as earlier, just pass the address

2025-01-29 09:59 UTC, Srihari-mcw commented on src/modules/rppt_tensor_bitwise_operations.cpp
> +    RppLayoutParams layoutParams = get_layout_params(srcDescPtr->layout, srcDescPtr->c);
![image](https://github.com/user-attachments/assets/df5779c4-dfe4-47b6-88e2-6ab1c4379090)
Add these conditions after a blank line and leave a blank line after these conditions - Add also for bitwise and, bitwise or

2025-01-29 10:00 UTC, Srihari-mcw requested changes
Please address review comments

2025-01-29 13:14 UTC, Srihari-mcw commented on src/modules/hip/kernel/bitwise_and.hpp
> +__device__ void bitwise_and_hip_compute(d_uchar8 *src1_uc8, d_uchar8 *src2_uc8, d_uchar8 *dst_uc8)
/media/rpp/src/modules/hip/kernel/bitwise_xor.hpp:63:5: error: no matching function for call to 'rpp_hip_load8_to_uchar8'                                                 63 |     rpp_hip_load8_to_uchar8(srcPtr2 + srcIdx, src2_uc8);                                                                                                             |     ^~~~~~~~~~~~~~~~~~~~~~~                                                                                                                                    /media/rpp/src/include/hip/rpp_hip_common.hpp:1344:33: note: candidate function not viable: no known conversion from 'd_uchar8' to 'uchar *' (aka 'unsigned char *') for 2nd argument                                                                                                                                                         1344 | __device__ __forceinline__ void rpp_hip_load8_to_uchar8(uchar *srcPtr, uchar *srcPtr_uc8)      

Leads to error and hence not needed

2025-01-29 13:15 UTC, Srihari-mcw commented on src/modules/hip/kernel/bitwise_or.hpp
> +    uchar* src1Ptr_uc8 = (uchar*)&src1_uc8;
/media/rpp/src/modules/hip/kernel/bitwise_xor.hpp:63:5: error: no matching function for call to 'rpp_hip_load8_to_uchar8'                                                 63 |     rpp_hip_load8_to_uchar8(srcPtr2 + srcIdx, src2_uc8);                                                                                                             |     ^~~~~~~~~~~~~~~~~~~~~~~                                                                                                                                    /media/rpp/src/include/hip/rpp_hip_common.hpp:1344:33: note: candidate function not viable: no known conversion from 'd_uchar8' to 'uchar *' (aka 'unsigned char *') for 2nd argument                                                                                                                                                         1344 | __device__ __forceinline__ void rpp_hip_load8_to_uchar8(uchar *srcPtr, uchar *srcPtr_uc8)      

Leads to issues and can be ignored

2025-01-29 13:38 UTC, Srihari-mcw commented
Please check for the earlier load/store float based routines to check feasibility of it being removed

2025-02-19 05:27 UTC, r-abishek requested changes
@Srihari-mcw Minor fixes - Lets do a global search for 'logical' just to ensure all tensor instances are changed to bitwise

2025-02-19 05:27 UTC, r-abishek commented on src/modules/cpu/kernel/bitwise_or.hpp
> +/* bitwiseOR is logical operation only on U8 types.*/
same comment

2025-02-19 05:36 UTC, merged