Test suite error detection enhancement
r-abishek/rpp pull request #350
Opened 2024-10-03 05:52 UTC by Dineshbabu-Ravichandran

- Made changes to detect the errors in image HIP and HOST test suites and print them at the end

2024-10-03 11:42 UTC, HazarathKumarM reviewed
@Dineshbabu-Ravichandran  please resolve the comments

2024-10-03 11:42 UTC, HazarathKumarM commented on utilities/test_suite/common.py
> +    if return_code < 0:
please use camel case for all  variables

2024-11-20 08:39 UTC, r-abishek commented on utilities/test_suite/HOST/runTests.py
> +        else :
No space before colon. Same on L333

2024-11-20 08:46 UTC, r-abishek commented on utilities/test_suite/HOST/runTests.py
> +                        log_detected_errors("Returned non-zero exit status : "+ str(exitCode) + " " + stderrData.decode(), errorLog, imageAugmentationMap[int(case)][0], get_bit_depth(int(bitDepth)),
L76-L80 is repeating almost 36 times in this PR with minor changes in arguments, can we consolidate to put it in one function in common.py?

2024-11-20 08:47 UTC, r-abishek requested changes
@Dineshbabu-Ravichandran Pls address comments

2024-11-26 17:09 UTC, r-abishek approved these changes
@Dineshbabu-Ravichandran @HazarathKumarM  Hope all HIP/HOST tests are passing for this PR.

2024-11-26 17:09 UTC, merged