AVX optimizations for brightness U8 and F32 variants
r-abishek/rpp pull request #45
Opened 2022-01-21 03:52 UTC by sampath1117

2022-01-24 23:39 UTC, r-abishek requested changes

2022-01-24 23:39 UTC, r-abishek commented on src/modules/cpu/host_tensor_augmentations.hpp
> +                    p[0] = _mm256_fmadd_ps(p[0], pBrightnessParams[0], pBrightnessParams[1]);    // brightness adjustment
Lets create a compute function in rpp_cpu_common for the brightness adjustment. Like in color twist

2022-01-24 23:39 UTC, r-abishek commented on src/modules/cpu/host_tensor_augmentations.hpp
>                      p[0] = _mm_fmadd_ps(p[0], pMul, pAdd);    // brightness adjustment Rs
Please add compute functions for the sse too

2022-01-24 23:39 UTC, r-abishek commented on src/modules/cpu/host_tensor_augmentations.hpp
> +        // Brightness without fused output-layout toggle (NHWC -> NHWC)
Can we retain the previous brightness execution style rather than separating them out for these cases?

2022-01-24 23:39 UTC, r-abishek commented on src/modules/cpu/host_tensor_augmentations.hpp
> +        else
Retaining the previous execution style should be able to handle the single-channel cases too under the same branch.

2022-01-25 10:36 UTC, sampath1117 commented
Closing the pull request. since other kernel changes are also reflected in same branch
created new PR with brightness changes alone
[https://github.com/r-abishek/rpp/pull/46](https://github.com/r-abishek/rpp/pull/46)

2022-01-25 10:36 UTC, closed without merging