AVX2 support for Brightness
r-abishek/rpp pull request #46
Opened 2022-01-25 10:35 UTC by sampath1117

*Added for U8 , F32 , I8 , F16 variants
*added for PKD3,PLN3,PLN1 with toggle

2022-02-02 23:05 UTC, r-abishek requested changes
Please take a look at the changes needed.

2022-02-02 23:05 UTC, r-abishek commented on src/include/cpu/rpp_cpu_common.hpp
> +inline RppStatus compute_brightness_24_host(__m256 &pVecR, __m256 &pVecG, __m256 &pVecB, __m256 *pBrightnessParams)
This file has a lot of BatchPD and Tensor functions. Could you add the new tensor functions needed right under L2069? Latest one first - so right above the compute_gridmask_masks_16_host(). We'll fix this during a restructure.

2022-02-03 17:19 UTC, sampath1117 commented
Made changes based on the review comments @r-abishek

2022-02-17 21:29 UTC, r-abishek approved these changes

2022-02-17 21:30 UTC, merged