AVX optimizations for Exposure kernel
r-abishek/rpp pull request #47
Opened 2022-02-02 07:06 UTC by sampath1117

*Added for U8 , F32 , I8 , F16 variants
*added for PKD3,PLN3,PLN1 with toggle

2022-02-02 23:48 UTC, r-abishek requested changes
merge conflicts

2022-02-03 14:51 UTC, sampath1117 commented
Resolved the merge conflicts @r-abishek

2022-02-19 01:28 UTC, r-abishek requested changes
A few minor formatting changes

2022-02-19 01:28 UTC, r-abishek commented on src/modules/rppt_tensor_color_augmentations.cpp
> +rppt_exposure_host(RppPtr_t srcPtr,
Format the rppt_ right next to RppStatus on previous line

2022-02-19 01:28 UTC, r-abishek commented on src/modules/cpu/kernel/exposure.hpp
> +
Remove extra blank line

2022-02-19 06:44 UTC, sampath1117 commented
Resolved the review comments @r-abishek

2022-02-23 18:33 UTC, r-abishek approved these changes

2022-02-23 18:34 UTC, merged