Vectorized implementation for Exposure kernel - HI
r-abishek/rpp pull request #50
Opened 2022-02-14 09:41 UTC by sampath1117

*Added for U8 , F32 , I8 , F16 variants
*added for PKD3,PLN3,PLN1 with toggle

2022-02-19 02:02 UTC, r-abishek requested changes
Please check performance without pow inside the kernel and address comments

2022-02-21 16:59 UTC, sampath1117 commented on src/modules/hip/kernel/exposure.hpp
> +    float multiplyingFactor = pow((float)2.0, exposureFactorTensor[id_z]);
I have checked the performance with both LUT and pow outside kernel and observed that  there is no significant improvement in performance

2022-02-23 18:35 UTC, r-abishek commented
@sampath1117 Could you resolve the conflicts?

2022-02-23 22:44 UTC, r-abishek approved these changes

2022-02-23 22:57 UTC, merged