Test suite modifications
r-abishek/rpp pull request #66
Opened 2022-04-04 13:21 UTC by sampath1117

*Added support to tensor unittests to accept user input for augmentation params

2022-04-06 03:42 UTC, r-abishek requested changes
Please take a look at these

2022-04-06 03:42 UTC, r-abishek commented on utilities/rpp-unittests/HOST_NEW/Tensor_host_pkd3.cpp
>          strcpy(funcName, "brightness");
If the "funcName" comes in as a string from the testAllScript.sh, then this first switch case can be entirely avoided.
You could introduce the default value or the user input value to each param directly inside the second switch case.

2022-04-06 03:42 UTC, r-abishek commented on utilities/rpp-unittests/HOST_NEW/Tensor_host_pkd3.cpp
> +            pBrightness[0] = atof(argv[8]);
You may want to add small validator macros or functions (to validate if the user input is in the correct range) in a separate header file and include that here. A common header file that will have helper functions, #defines and includes common to all files.

2022-04-06 03:42 UTC, r-abishek commented on utilities/rpp-unittests/HOST_NEW/Tensor_host_pkd3.cpp
> +            alpha[i] = pBrightness[0];
After input validation passes, the user param can be used directly. Even if one of the params fails validation, force the user to enter correct params. If no params are entered by the user at all, only then the default params should run.

2022-04-06 03:42 UTC, r-abishek commented on utilities/rpp-unittests/HOST_NEW/testAllScript.sh
> +        read -p "$varNames" USER_INPUT_ARGUMENTS[CASE_INDEX]
Could you confirm if these work - the unit test suite should run in the scenarios:
- running single case - with user params or default values
- running say a couple cases - say 3 cases (./testAllScript 0 2 0 to run case 0, 1, 2) - with user params or default values
- And finally, the all-cases output test where we just run ./testAllScript.sh should run ideally with just the default values like it does now.

2023-01-06 10:13 UTC, sampath1117 commented
Closing the PR since this branch became obsolete
Issued a new PR here
https://github.com/r-abishek/rpp/pull/108

2023-01-06 10:13 UTC, closed without merging